name: Run Tests
  
on: [workflow_dispatch, push]  
  
jobs:  
  build:  
    runs-on: self-hosted  
    strategy:  
      matrix:  
        python-version: ["3.11.2"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip --break-system-packages
          if [ -f requirements.txt ]; then pip install -r requirements.txt --break-system-packages; fi; pip install coverage --break-system-packages; pip install pytest --break-system-packages; export PYTHONIOENCODING=utf8;
      - name: Build and Flash STM32_FW 
        run: |  
          cd src/STM32_FW;make;cp build/STM32_FW_F7.elf ../xpacks/.bin/STM32_FW.elf;cd ../xpacks/.bin;
          sudo ./openocd -s "/usr/local/share/openocd/scripts" -f "interface/stlink-v2.cfg" -f "target/stm32f7x.cfg" -c "program STM32_FW.elf verify reset exit";
      - name: Test with pytest  
        run: |  
          python -m coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          python -m coverage report -m
